### PR TITLE
Added support for h1 tags & rebranded for magnet.me

### PR DESCRIPTION
**Pull request by TiddoLangerak**
I don't think it's very useful for @Magnetme/monolith  to review this, since it's all coffeescript and in an unknown project. 

I do need to publish this though for our own usage. We can do this to our private repo, or just to the public one. I have no problem just pushing it to the public repository, and I think @rogierslag would also prefer that because of ops.

cc @wouter-willems

### CODE REVIEW

**Comment by TiddoLangerak** [comment]
The reason for changes written in the commits by the way, so if you want to know why I did stuff you should read those.

**Comment by alexnederlof** [comment]
You can just push it to our npm registry right?

**Comment by TiddoLangerak** [comment]
Yes

**Comment by rogierslag** [comment]
For ops I dont really care, or do we need to pull this on some production servers as well?

**Comment by AlexKolpa** [comment]
I think he meant because of your request that we eventually drop our internal npm registry

**Comment by wouter-willems** [comment]
:+1: and yeah, just publish to public

**Pull request merged**
